FROM gableroux/flutter

LABEL version="1.0.0"
LABEL name="flutter"
LABEL repository="https://github.com/sarinupreti/CRUD-App"
LABEL homepage="https://github.com/sarinupreti/CRUD-App"

LABEL maintainer="Luca Steeb <contact@luca-steeb.com>"
LABEL com.github.actions.name="Flutter CLI"
LABEL com.github.actions.description="Provides the flutter binary to test and build your app."
LABEL com.github.actions.icon="terminal"
LABEL com.github.actions.color="purple"

COPY LICENSE README.md /

ENTRYPOINT ["flutter"]
CMD ["help"]
